paths:
  /api/products:
    get:
      summary: Obtiene todos los products
      tags:
        - products
      responses:
        '200':
          description: Los products fueron devueltos satisfactoriamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/products'
        '404':
          description: Error al obtener la informacion
        '500':
          description: Error del servidor. Usualmente generando la query o falla la conexion a la DB
    post:
      summary: Crea un nuevo producto
      tags:
        - products
      operationId: addProduct
      requestBody:
        description: Producto agregado a la tienda
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/newProduct'
      responses:
        '200':
          description: producto agregado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/products'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/products/{_id}:
    get:
      summary: Obtiene un producto por su ID
      tags:
        - products
      parameters:
        - name: _id
          in: path
          required: true
          description: ID del usuario que se busca
          schema:
            $type: String
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: '#components/schemas/products'
    put:
      summary: Actualizar un products a partir del ID
      tags:
        - products
      parameters:
        - name: _id
          in: path
          required: true
          description: ID del usuario que se busca
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateproducts'
      responses:
        '200':
          description: Usuario modificado exitosamente
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Success'
    delete:
      summary: elimina un producto por su ID
      tags:
        - products
      operationId: deleteProduct
      parameters:
        - name: _id
          in: path
          description: ID of product to delete
          required: true
      responses:
        '204':
          description: product deleted
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Success:
      type: object
      properties:
        status:
          type: String
          description: success or error
        code:
          type: Number
          description: código de respuesta HTTP.
        payload:
          type: Array
          description: array con la informacion de la peticion requerida
        message:
          type: String
          description: aclarando que ocurrio
      example:
        status: success
        code: 201
        payload: {}
        message: products updated
    products:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID auto generado by mongo
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion breve del producto
        category:
          type: String
          description: Categoria del producto
        price:
          type: String
          description: Precio del producto
        thumbnail:
          type: String
          description: Imagen del producto
        code:
          type: String
          description: Codigo unico del producto
        owner:
          type: String
          description: Email del propietario del producto
        stock:
          type: Number
          description: Unidades totales disponibles
      example:
        _id: ObjectId("644081a93f0625dc193bc594")
        title: 'Salad'
        description: 'The beautiful range of Apple Naturalé that has an exciting mix of natu…'
        category: 'Baby'
        price: '$550'
        thumbnail: 'insight_schedule_bloop.jpg'
        code: '1oOXBRaLHw'
        owner: atrian@gmail.com
        stock: 15
    newProduct:
      type: object
      required:
        - title
        - description
        - category
        - price
        - thumbnail
        - code
        - owner
        - stock
      properties:
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion breve del producto
        category:
          type: String
          description: Categoria del producto
        price:
          type: String
          description: Precio del producto
        thumbnail:
          type: String
          description: Imagen del producto
        code:
          type: String
          description: Codigo unico del producto
        owner:
          type: String
          description: Email del propietario del producto
        stock:
          type: Number
          description: Unidades totales disponibles
  requestBodies:
    updateproducts:
      type: object
      properties:
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion breve del producto
        category:
          type: String
          description: Categoria del producto
        price:
          type: String
          description: Precio del producto
        thumbnail:
          type: String
          description: Imagen del producto
        code:
          type: String
          description: Codigo unico del producto
        owner:
          type: String
          description: Email del propietario del producto
        stock:
          type: Number
          description: Unidades totales disponibles
      example:
        title: 'Salad'
        description: 'The beautiful range of Apple Naturalé that has an exciting mix of natu…'
        category: 'Baby'
        price: '$550'
        thumbnail: 'insight_schedule_bloop.jpg'
        code: '1oOXBRaLHw'
        owner: atrian@gmail.com
        stock: 15
  Error:
    type: object
    required:
      - id
    properties:
      id:
        type: ObjectId
